-- =====================================================
-- USUÁRIOS E IDENTIDADE
-- =====================================================

create table public.usuarios (
                                 id_usuario integer generated by default as identity not null,
                                 nome character varying(100) null,
                                 email character varying(150) null,
                                 auth_id uuid not null,
                                 constraint usuario_pkey primary key (id_usuario),
                                 constraint usuario_auth_id_key unique (auth_id),
                                 constraint usuario_email_key unique (email)
) TABLESPACE pg_default;


-- =====================================================
-- ALIMENTAÇÃO E DESAFIO DA MERENDA
-- =====================================================

create table public.alimentos (
                                  id_alimento integer generated by default as identity not null,
                                  nome character varying(100) null,
                                  is_healthy boolean null,
                                  imagem_url character varying(255) null,
                                  constraint alimentos_pkey primary key (id_alimento)
) TABLESPACE pg_default;

create table public.selecao_alimento (
                                         id_selecao integer generated by default as identity not null,
                                         id_usuario integer null,
                                         id_alimento integer null,
                                         data_hora timestamp without time zone null,
                                         acertou boolean null,
                                         id_resultado integer null,
                                         constraint selecao_alimento_pkey primary key (id_selecao),
                                         constraint selecao_alimento_id_alimento_fkey foreign KEY (id_alimento) references alimentos (id_alimento),
                                         constraint selecao_alimento_id_resultado_fkey foreign KEY (id_resultado) references resultado_pergunta (id_resultado),
                                         constraint selecao_alimento_id_usuario_fkey foreign KEY (id_usuario) references usuarios (id_usuario)
) TABLESPACE pg_default;


-- =====================================================
-- MISSÕES, QUESTÕES E GAMIFICAÇÃO
-- =====================================================

create table public.missao (
                               id_missao integer generated by default as identity not null,
                               titulo character varying(100) null,
                               descricao text null,
                               pontos bigint not null default 0,
                               constraint missao_pkey primary key (id_missao)
) TABLESPACE pg_default;

create table public.questao_missao (
                                       id_questao integer generated by default as identity not null,
                                       id_missao integer null,
                                       enunciado text null,
                                       constraint questao_missao_pkey primary key (id_questao),
                                       constraint questao_missao_id_missao_fkey foreign KEY (id_missao) references missao (id_missao)
) TABLESPACE pg_default;

create table public.alternativa_missao (
                                           id_alternativa integer generated by default as identity not null,
                                           id_questao integer null,
                                           texto text null,
                                           correta boolean null,
                                           feedback text null,
                                           constraint alternativa_missao_pkey primary key (id_alternativa),
                                           constraint alternativa_missao_id_questao_fkey foreign KEY (id_questao) references questao_missao (id_questao)
) TABLESPACE pg_default;

create table public.resposta_usuario_missao (
                                                id_resposta integer generated by default as identity not null,
                                                id_usuario integer null,
                                                id_alternativa integer null,
                                                data_hora timestamp without time zone null,
                                                id_missao bigint not null,
                                                data_dia date GENERATED ALWAYS as ((data_hora)::date) STORED null,
  constraint resposta_usuario_missao_pkey primary key (id_resposta),
  constraint unica_resposta_por_missao_por_dia unique (id_usuario, id_missao, data_dia),
  constraint fk_resposta_usuario_missao_missao foreign KEY (id_missao) references missao (id_missao) on delete CASCADE,
  constraint resposta_usuario_missao_id_alternativa_fkey foreign KEY (id_alternativa) references alternativa_missao (id_alternativa),
  constraint resposta_usuario_missao_id_usuario_fkey foreign KEY (id_usuario) references usuarios (id_usuario)
) TABLESPACE pg_default;

create table public.resultado_pergunta (
                                           id_resultado integer generated always as identity not null,
                                           id_usuario integer null,
                                           pontos integer not null,
                                           total_selecionados integer null,
                                           total_corretos integer null,
                                           data_hora timestamp without time zone null default now(),
                                           constraint resultado_pergunta_pkey primary key (id_resultado),
                                           constraint resultado_pergunta_id_usuario_fkey foreign KEY (id_usuario) references usuarios (id_usuario)
) TABLESPACE pg_default;


-- =====================================================
-- ATIVIDADE FÍSICA
-- =====================================================

create table public.atividade_fisica (
                                         id_atividade integer generated by default as identity not null,
                                         name character varying(50) null,
                                         points integer null,
                                         subtitle character varying(100) null,
                                         emoji character varying(10) null,
                                         constraint atividade_fisica_pkey primary key (id_atividade)
) TABLESPACE pg_default;

create table public.atividade_realizada (
                                            id_realizada integer generated by default as identity not null,
                                            id_usuario integer null,
                                            id_atividade integer null,
                                            data_hora timestamp without time zone null,
                                            constraint atividade_realizada_pkey primary key (id_realizada),
                                            constraint atividade_realizada_id_atividade_fkey foreign KEY (id_atividade) references atividade_fisica (id_atividade),
                                            constraint atividade_realizada_id_usuario_fkey foreign KEY (id_usuario) references usuarios (id_usuario)
) TABLESPACE pg_default;

create unique index if not exists uniq_atividade_realizada_por_dia
    on public.atividade_realizada using btree (id_usuario, id_atividade, ((data_hora)::date));


-- =====================================================
-- GLICEMIA E HUMOR
-- =====================================================

create table public.glicemia (
                                 id_glicemia integer generated by default as identity not null,
                                 id_usuario integer null,
                                 valor_mgdl numeric(5, 2) null,
                                 data_hora timestamp with time zone null default now(),
                                 periodo integer not null,
                                 descricao_periodo character varying(50) not null,
                                 constraint glicemia_pkey primary key (id_glicemia),
                                 constraint glicemia_id_usuario_fkey foreign KEY (id_usuario) references usuarios (id_usuario) on delete CASCADE
) TABLESPACE pg_default;

create table public.humor_diario (
                                     id_humor integer generated by default as identity not null,
                                     id_usuario integer null,
                                     data date null,
                                     estado character varying not null,
                                     constraint humor_diario_pkey primary key (id_humor),
                                     constraint humor_diario_id_usuario_fkey foreign KEY (id_usuario) references usuarios (id_usuario) on delete CASCADE
) TABLESPACE pg_default;

create unique index if not exists humor_unico_por_dia
    on public.humor_diario using btree (id_usuario, data);


-- =====================================================
-- MEDICAÇÃO
-- =====================================================

create table public.remedio (
                                id_remedio integer generated by default as identity not null,
                                nome character varying null,
                                horario time without time zone null,
                                ativo boolean null,
                                criado_em timestamp without time zone null,
                                id_usuario integer not null,
                                constraint remedio_pkey primary key (id_remedio),
                                constraint fk_remedios_usuario foreign KEY (id_usuario) references usuarios (id_usuario) on delete CASCADE
) TABLESPACE pg_default;

create table public.registro_medicacao (
                                           id_registro integer generated by default as identity not null,
                                           id_usuario integer null,
                                           id_lembrete integer null,
                                           data_hora timestamp without time zone null,
                                           tomou boolean null,
                                           constraint registro_medicacao_pkey primary key (id_registro),
                                           constraint registro_medicacao_id_lembrete_fkey foreign KEY (id_lembrete) references lembrete_medicacao (id_lembrete),
                                           constraint registro_medicacao_id_usuario_fkey foreign KEY (id_usuario) references usuarios (id_usuario)
) TABLESPACE pg_default;

create table public.remedio_uso (
                                    id_uso integer generated by default as identity not null,
                                    id_remedio integer null,
                                    id_usuario integer null,
                                    data_hora timestamp without time zone null,
                                    confirmado boolean null,
                                    data_br date null,
                                    constraint remedio_uso_pkey primary key (id_uso),
                                    constraint remedio_uso_id_remedio_fkey foreign KEY (id_remedio) references remedio (id_remedio),
                                    constraint remedio_uso_id_usuario_fkey foreign KEY (id_usuario) references usuarios (id_usuario)
) TABLESPACE pg_default;

create unique index if not exists unico_uso_por_dia
    on public.remedio_uso using btree (id_usuario, id_remedio, data_br);

create trigger trg_set_data_br
    before insert on remedio_uso
    for each row execute function set_data_br();


-- =====================================================
-- CUIDADOS DIÁRIOS E PROTEÇÃO
-- =====================================================

create table public.cuidados_diarios (
                                         id bigint generated always as identity not null,
                                         titulo character varying(255) not null,
                                         descricao text null,
                                         icone character varying(100) null,
                                         ordem integer not null,
                                         ativo boolean not null default true,
                                         created_at timestamp with time zone null default now(),
                                         constraint cuidados_diarios_pkey primary key (id)
) TABLESPACE pg_default;

create table public.usuario_cuidados (
                                         id bigint generated always as identity not null,
                                         id_usuario bigint not null,
                                         cuidado_id bigint not null,
                                         data date not null,
                                         concluido boolean not null default false,
                                         concluido_em timestamp with time zone null,
                                         constraint usuario_cuidados_pkey primary key (id),
                                         constraint unique_usuario_cuidado_data unique (id_usuario, cuidado_id, data),
                                         constraint fk_usuario_cuidados_cuidado foreign KEY (cuidado_id) references cuidados_diarios (id) on delete CASCADE,
                                         constraint fk_usuario_cuidados_usuario foreign KEY (id_usuario) references usuarios (id_usuario) on delete CASCADE
) TABLESPACE pg_default;

create table public.nivel_protecao (
                                       id bigint generated always as identity not null,
                                       usuario_id bigint not null,
                                       data date not null,
                                       total_cuidados integer not null,
                                       cuidados_concluidos integer not null,
                                       nivel_percentual integer not null,
                                       constraint nivel_protecao_pkey primary key (id),
                                       constraint unique_nivel_usuario_data unique (usuario_id, data),
                                       constraint fk_nivel_protecao_usuario foreign KEY (usuario_id) references usuarios (id_usuario) on delete CASCADE
) TABLESPACE pg_default;
